ALTER TYPE "CandidateStage" ADD VALUE IF NOT EXISTS 'PROFILE_COMPLETE';
ALTER TYPE "CandidateStage" ADD VALUE IF NOT EXISTS 'SHORTLISTED';
ALTER TYPE "CandidateStage" ADD VALUE IF NOT EXISTS 'CLIENT_INTERVIEW';
ALTER TYPE "CandidateStage" ADD VALUE IF NOT EXISTS 'OFFERED';

ALTER TYPE "SubmissionStatus" ADD VALUE IF NOT EXISTS 'CLIENT_INTERVIEW_SCHEDULED';
ALTER TYPE "SubmissionStatus" ADD VALUE IF NOT EXISTS 'CLIENT_INTERVIEW_COMPLETED';
ALTER TYPE "SubmissionStatus" ADD VALUE IF NOT EXISTS 'CLIENT_SELECTED';
ALTER TYPE "SubmissionStatus" ADD VALUE IF NOT EXISTS 'OFFER_RELEASED';
ALTER TYPE "SubmissionStatus" ADD VALUE IF NOT EXISTS 'WITHDRAWN';
